### ISSUE TITLE
Chrome with stored login credentials (Manage Passwords ON)

### ISSUE THREAD

**Issue by szediwy** [zkoss/zk#1028]
When the following ZUL page is opened and there is a user/password pair for the current domain the menu popup automatically closes right after opening it.

<zk xmlns="http://www.zkoss.org/2005/zul"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.zkoss.org/2005/zul http://www.zkoss.org/2005/zul/zul.xsd">

    <div hflex="1" vflex="1">

        <menubar>
            <menu label="X">
                <menupopup>
                    <menuitem label="A"></menuitem>
                    <menuitem label="B"></menuitem>
                    <menuitem label="C"></menuitem>
                </menupopup>
            </menu>
        </menubar>

        <textbox id="user"></textbox>
        <textbox id="password" type="password"></textbox>

    </div>
</zk>

[movie.zip](https://github.com/zkoss/zk/files/1686052/movie.zip)

**Comment by szediwy** [comment]
If the password textbox is removed the menu popup works correctly.

**Comment by szediwy** [comment]
<textbox id="password" type="password" xmlns:ca="client/attribute" ca:autocomplete="new-password"></textbox> 
solved the issue

**Comment by cor3000** [comment]
thanks for posting the issue, we tracked it as [ZK-3862](http://tracker.zkoss.org/browse/ZK-3862)
