### ISSUE TITLE
bookmark with slash charactor

### ISSUE THREAD

**Issue by sytv38** [zkoss/zk#1284]
Hi all,
I'm using bookmark with Executions.getCurrent().getDesktop().setBookmark("/error/404") but when it show on browser: http://localhost:8080/#%2Ferror%2F404.

I want show on browser: http://localhost:8080/#/error/404
Has solution?

**Comment by scribetw** [comment]
Thanks for the report.
Created an issue on our JIRA tracker instead: https://tracker.zkoss.org/browse/ZK-4141
