### ISSUE TITLE
Make pickers compatible with java 8 date types

### ISSUE THREAD

**Issue by Yann39** [zkoss/zk#1521]
I have multiple issues related to dates when using new Java 8 API (i.e. `LocalDateTime`, `LocalDate` or `LocalTime`) as ZK date and time pickers return _old_ `Date` objects. So when a value is selected from a picker it cannot be converted :

> Cannot convert 22.01.19 08:31 of type class java.util.Date to class java.time.LocalDateTime

I also cannot use some properties in pickers as it is waiting for a `Date` (i.e. `min` and `max` properties in time picker) : 

> java.lang.ClassCastException: 12:00(java.time.LocalTime) cannot be converted to class java.util.Date

Same for the built-in `formatedDate` formatter, which uses `Date` (I had to build a custom one).

So I always need to do the cast in my viewmodels to make it work.

Is there any workaround ?

Another problem is that even when using `Date` types in my viewmodels/entities, I cannot use it in a form when it is mapped to a database Time object (using JPA annotation `@Temporal(TemporalType.TIME)` because it seems the form proxy object does not support it:

Example:

```
@Entity
@Table(name = "schedule")
public class Schedule {

    @Column
    @Temporal(TemporalType.DATE)
    private Date day;

    @Column
    @Temporal(TemporalType.TIME)
    private Date start;

    @Column
    @Temporal(TemporalType.TIME)
    private Date end;
}
```

```
<div form="@id('course') @load(myVm.course) @save(myVm.course, before={'saveCourse'})">
    <forEach items="@load(course.schedules)">
        <hlayout>
            <label value="@load(each.day)"/>
            <label value="@load(each.start)"/>
            <label value="@load(each.end)"/>
        </hlayout>
    </forEach>
</div>
```

As soon as I try to display `start` or `end`, I get:

> java.lang.NoClassDefFoundError: org/zkoss/bind/proxy/FormProxyObject

Works fine for the `day`.

So here are my requirements:
- Allow pickers to return java 8 date types
- Update converters to support Java 8 date types (and on the way rename "formated" to "format**t**ed" :))
- Support Java 8 date types in picker properties (`min`, `max`, etc.)
- Support Date mapped to a Time in form proxy objects

**Comment by scribetw** [comment]
Hi, please see #1705 and #1696.  

About this issue:
> java.lang.NoClassDefFoundError: org/zkoss/bind/proxy/FormProxyObject

Please provide a reproducible minimal project for debugging. Thanks.
