### ISSUE TITLE
ZK Maven BOM

### ISSUE THREAD

**Issue by aljiru** [zkoss/zk#1767]
It would be nice to have a maven bom (bill of materials).
See:
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html
https://repo1.maven.org/maven2/org/springframework/spring-framework-bom/5.2.0.RELEASE/spring-framework-bom-5.2.0.RELEASE.pom

so that one could just import the bom to define dependency management for ZK dependencies.

**Comment by scribetw** [comment]
Thanks for the suggestion. It seems like a good idea for transitive dependencies.

**Comment by cor3000** [comment]
FR [ZK-4458](https://tracker.zkoss.org/browse/ZK-4458)
