### ISSUE TITLE
zk timer edge

### ISSUE THREAD

**Issue by typik89** [zkoss/zk#1823]
ZK 8.0.1
I use on my page:
<timer id="refreshTimer" running="true" delay="5000" onTimer="@command( 'refresh' )" repeats="true" />

If I use Chrome, I can see that data on my page is updated when my focus on another window.
But if use Microsoft Edge, updates on my page happen only if I have a focus on the Edge browser.

Why does it work in a different way on Microsoft Edge?

**Comment by scribetw** [comment]
https://www.zkoss.org/zkdemo/server_push/timer

I can't reproduce on Edge 18. The inactive tab is still updated.
Can you provide more information?

**Comment by typik89** [comment]
I can't reproduce now. Maybe It happened because of a session timeout.
