### ISSUE TITLE
Websocket failure when desktop recycled (DesktopRecycle listener activated)

### ISSUE THREAD

**Issue by amusaku** [zkoss/zk#1830]
1. zk Version 9.0.0-EVAL
2. Project example zk-rxdemo

I have configured the zk.xml with 
`	<listener>
		<listener-class>org.zkoss.zkmax.ui.util.DesktopRecycle</listener-class>
	</listener>`

The application fails when the desktop is recycled, it works when i activate the Comet or Pollingserverpush.

**Comment by cor3000** [comment]
posted BUG [ZK-4460](https://tracker.zkoss.org/browse/ZK-4460)
please follow/continue the status there
