### ISSUE TITLE
listitem event onDoubleClick doesn't work

### ISSUE THREAD

**Issue by sesong11** [zkoss/zk#1835]
<template name="model">
	<listitem onDoubleClick="@command('command' ...

After update to zk 9 event double doesn't work anymore.

**Comment by sesong11** [comment]
Another components such as Button & A do not trigger double click event too.

**Comment by scribetw** [comment]
Please use our JIRA tracker to report anything instead of GitHub issues.

http://zkfiddle.org/sample/16q4flf/1-zk-issues-1835
I can't reproduce it.
Please provide more information like what browser are you using or a reproducible zul example.

**Comment by sesong11** [comment]
Sorry It was my bad, after I clear browser cache it work for all browsers.
thanks
