### ISSUE TITLE
ZK 9 Notification.show with 0 duration not close when click outside box

### ISSUE THREAD

**Issue by sesong11** [zkoss/zk#1836]
after update to zk 9 `Notification.show` & `Client.showNotification` with duration 0 do not close when we click outside notification box.

`Notification.show(message, "warning", null, "middle_center", 0);`

**Comment by scribetw** [comment]
http://zkfiddle.org/sample/24o7lqp/1-zk-issues-1836

I cannot reproduce it.
Please provide more information like in which browser or what components did you use?

**Comment by sesong11** [comment]
https://github.com/sesong11/zulondb/blob/master/src/main/java/com/example/zumlondb/vm/MainVM.java

This's run able code, Notification show on home page init, but it not close when using Google Chrome 79, another browser work fine.

**Comment by sesong11** [comment]
Sorry It was my bad, after I clear browser cache it work for all browsers.
thanks
