### ISSUE TITLE
Configure repositories to use HTTPS

### ISSUE THREAD

**Issue by aljiru** [zkoss/zk#1850]
As you might know public repositories are trying to make dependency loading safer by restricting access only through HTTPS:
https://twitter.com/JLLeitschuh/status/1214938830983311361
https://central.sonatype.org/articles/2019/Apr/30/http-access-to-repo1mavenorg-and-repomavenapacheorg-is-being-deprecated/

It's great that your documentation suggest configuring repos through HTTPS (https://www.zkoss.org/wiki/ZK_Installation_Guide/Setting_up_IDE/Maven/Resolving_ZK_Framework_Artifacts_via_Maven), but scanning your public repo I can see almost all repository definitions keep using unsafe HTTP. Maybe you should consider updating them. I used this query to search all repository definitions:
https://github.com/search?l=Maven+POM&q=org%3Azkoss+repository&type=Code

I can provide some PR's if you want some help, but fixing it should be easy.

**Comment by scribetw** [comment]
Yes, we should update our POM files since we definitely provide HTTPS access.

I'll create an issue in our tracker and fix it. Thanks.
