### ISSUE TITLE
Combobox item autodropdown on element load

### ISSUE THREAD

**Issue by AlexIvan2** [zkoss/zk#1874]
After migrating from ZK version 8.5.0 to 8.6.0.1, we faced the issue with Combobox elements only in IE browser. 
By some reason, it can't be re-created in ZK fiddle, so let me just paste my small demo code here to be clear.
Simple ZUL with combobox element:
```
<zk>
    <div apply="org.zkoss.bind.BindComposer" height="278px" width="443px"
         viewModel="@id('vm') @init('com.swissre.cre.presentation.mvc.TestModel')">
        <combobox id="cmbColor" width="150px"
                  model="@load(vm.names)" selectedItem="@bind(vm.iname)">
        </combobox>
    </div>
</zk>
```

My test model:
```
public class TestModel {

    private String iname;
    private List<String> names = Arrays.asList("Iüvanov", "alex", "ivan");

    @Init
    public void init() {
        setIname("Iüvanov");
    }

    public List<String> getNames() {
        return names;
    }

    public void setNames(List<String> names) {
        this.names = names;
    }

    public String getIname() {
        return iname;
    }

    public void setIname(String iname) {
        this.iname = iname;
    }

}
```

If the selected value contains characters like this "ü" (or any other diaeresis characters), the dropdown will be triggered on page re-load (on F5 for instance). If you remove this char from collection element it will not happen.
I will be highly appreciated for any help with this issue.
Thank you in advance.

**Comment by scribetw** [comment]
I tried your example with ZK 8.6.0.1 and IE9.  I can't reproduce on my side.
![ezgif-6-5b091a5a7c54](https://user-images.githubusercontent.com/6398934/74300135-d6edfa00-4d89-11ea-84ce-0c4b5fb87e8d.gif)

**Comment by AlexIvan2** [comment]
We are working on IE11. Unfotunately, I don't have opportunity to test this on IE9. 

![2020-02-12_09-15-41](https://user-images.githubusercontent.com/29925917/74311520-5a9eeb00-4d78-11ea-8294-f5ae483c03f7.gif)

**Comment by cor3000** [comment]
https://forum.zkoss.org/question/112060/combobox-autodropdown-on-page-reload-issue-with-ie

**Comment by cor3000** [comment]
discussion stopped without conclusion in forum
