### ISSUE TITLE
Since ZK 9.0.0 There are some rendering problems

### ISSUE THREAD

**Issue by JoseWalker** [zkoss/zk#1990]
Starting from version 9.0.0 we'd experienced problems with rendering issues because sometimes we get an "empty" page until the browser or de window is resized. 

Also if you use flex or vflex it doesn't work properly, until one does a $(window).resize() within a zk aftermount in javascript. 

This behaviour prevents some events to be attached to buttons or other "call to action" elements within the page. 

What can be done in here?

**Comment by scribetw** [comment]
Track it here https://tracker.zkoss.org/browse/ZK-4573
