### ISSUE TITLE
Clones of Radiogroup are rendered with same name as the source.

### ISSUE THREAD

**Issue by moontide** [zkoss/zk#2038]
# Description #
After a radiogroup is cloned and rendered, the name of the two radiogroups are identical.

* ZK version: 9.0.0.1
* OS: Fedora Linux 32

# Code sample to reproduce this issue #

	<zk>
	<radiogroup id='rgLineType'>
		<radio label='application'/>
		<radio label='comment'/>
		<radio label='include'/>
		<radio label='#include'/>
	</radiogroup>
	<separator/>
	<label id='info'/>
	<separator/>
	<button label='Clone radiogroup' onClick='CloneRadiogroup(event)'/>
	<separator/>
	<zscript>
	void CloneRadiogroup (Event event)
	{
		Radiogroup rgNew = rgLineType.clone ();
		rgNew.setId (null);
		info.setValue ("name of source radiogroup is [" + rgLineType.name + "], name of clone is [" + rgNew.name + "]. seems different, but it is rendered as same name as the source: Click radio in the one radiogroup will clear selection in another radiogroup");
		event.getTarget().getParent().appendChild (rgNew);
	}
	</zscript>
	</zk>

**Comment by scribetw** [comment]
https://tracker.zkoss.org/browse/ZK-4619 We'll use JIRA to track it instead, thanks for reporting.
