### ISSUE TITLE
Supporting Jakarta EE namespace

### ISSUE THREAD

**Issue by strangelookingnerd** [zkoss/zk#2400]
Hello,
are there any plans to support jakarta.* namespace in the near future?

**Comment by scribetw** [comment]
Hi,
I'll create this issue in our JIRA: https://tracker.zkoss.org/browse/ZK-4797.

And yes we have plans to support Jakarta EE, meanwhile, we want to keep supporting old JavaEE too.

If you have any comments, please leave them in the issue, thank you.
