### ISSUE TITLE
Jakatra BOM

### ISSUE THREAD

**Issue by szymonk92** [zkoss/zk#2692]
It looks like Jakatra version is not always present in maven repository. Lets take latest [ZK BOM, 9.6.0.1-jakarta](https://mvnrepository.com/artifact/org.zkoss.zk/zk-bom/9.6.0.1-jakarta).

You can find a dependency `org.zkoss.theme » breeze | 9.6.0.1-jakarta` which seems to be missing in maven repository.
Is [breeze ](https://mvnrepository.com/artifact/org.zkoss.theme/breeze)released in 'Jakatra' version? 

And it's not the only one not found

**Comment by plijyfes** [comment]
Hi,

breeze and other themes does not released in 'Jakarta' version.

I created the issue in our JIRA: https://tracker.zkoss.org/browse/ZK-5056.

If you have any comments, please leave them in the issue, thank you.
