### ISSUE TITLE
Missing break or "fall through" comment in PageImpl.getAttributes()

### ISSUE THREAD

**Issue by digulla** [zkoss/zk#2725]
Why is PageImpl.getAttributes() returning the page's attributes when there is no desktop (line 446)?

https://github.com/zkoss/zk/blob/ba33dda96f8595800e7c6e85422a9293a7930413/zk/src/org/zkoss/zk/ui/impl/PageImpl.java#L434-L455

All other cases return an empty map.

Is that intentional? If so, I suggest to add a `// fall through` comment.

**Comment by jumperchen** [comment]
Looks like a bug, thanks for the info; I create an issue in our issue tracker - https://tracker.zkoss.org/browse/ZK-5080
Please follow it up there.
