### ISSUE TITLE
Not able to contact Jira administrators on https://tracker.zkoss.org/

### ISSUE THREAD

**Issue by Omcsesz** [zkoss/zk#2734]
Hello, Team!

When I click on "JIRA administrators" on https://tracker.zkoss.org/, I get an error message (see attachment).
Can you please fix this?

[ContactJIRAAdmins](https://user-images.githubusercontent.com/1839739/154951504-2aee9d3e-9c6a-4099-92c9-1d77ffe859a4.gif)

**Comment by hawkchen** [comment]
create an account in [our forum](http://www.zkoss.org/forum/signup.zul) then use the same account to login.
