### ISSUE TITLE
Paging does not seem to work in Listbox in ZK 8.0.1.1 CE.

### ISSUE THREAD

**Issue by dormitionskete** [zkoss/zk#690]
Paging doesn't seem to work in the listbox component any more.  I'm pretty sure this worked at one time in ZK 6.5.4 CE, but it is not working using ZK 8.0.1.1 CE.

If you click on any of the paging buttons, they flicker like they've been clicked, but nothing happens.

Has something changed, or am I implementing this wrong?

```

<listbox id="adminStaticPageListbox"
         model="${adminStaticPageWindow$composer.staticPageDataModel}"
         checkmark="false"
         mold="paging" pageSize="15"
         pagingPosition="both"
         width="600px" >
    <listhead>
        <listheader hflex="1"
                    label="PageID" align="left" />
        <listheader hflex="2"
                    label="Title" align="left" />
    </listhead>
    <template name="model">
        <listitem>
            <listcell
                label="${each.staticPageID}" style="text-align: left" />
            <listcell
                label="${each.staticPageTitle}" style="text-align: left" />
        </listitem>
    </template>
</listbox>


```

**Comment by DevChu** [comment]
Could you provide a runnable case? (for example, http://zkfiddle.org/)

**Comment by dormitionskete** [comment]
Wow!  That was a long time ago.  I remember having problems, as described in my first post, but I just made a test program for you, and everything seems to be working fine in 6.5.2CE, 8.0.1.1CE and 8.0.2.2CE.  I don't have any idea what I was doing differently last year.  

I guess you should feel free to close this.

Please forgive me for the trouble.

I appreciate you checking into it.
