### ISSUE TITLE
build by ant create a binary without folder css

### ISSUE THREAD

**Issue by hieplq** [zkoss/zk#800]
I build zk by travis but output binary miss css folder
example: 
on zul binary, normal have two folder /web/js/zul/mesh/less and /web/js/zul/mesh/css
but on my zul binary have only /web/js/zul/mesh/less

build log [here](https://travis-ci.org/hieplq/zk/builds/235486774)

output [here](https://github.com/hieplq/zk/releases/tag/v8.0.5.2)

what's step i miss?

**Comment by scribetw** [comment]
Since the old `zkless-engine` is manly for internal building, it needs zkmax path.

We've released version zkless-engine 1.0, which solved this issue.
