### ISSUE TITLE
 java.io.NotSerializableException: org.zkoss.zk.ui.http.SimpleSession

### ISSUE THREAD

**Issue by yorkane** [zkoss/zk#807]
18-Jun-2017 20:21:49.717 ?? [shiro-active%0053ession%0043ache.data] net.sf.ehcache.store.disk.DiskStorageFactory$DiskWriteTask.call Disk Write of cd950837-0783-419c-8633-edfbba3810bf failed: 
 java.io.NotSerializableException: org.zkoss.zk.ui.http.SimpleSession

When combing shiro and ZK, I've encountered this error.

The web.xml configuration as below:
    
    <listener>
        <listener-class>org.apache.shiro.web.env.EnvironmentLoaderListener</listener-class>
    </listener>
    <filter>
        <filter-name>ShiroFilter</filter-name>
        <filter-class>org.apache.shiro.web.servlet.ShiroFilter</filter-class>
        <init-param>
            <param-name>ignore</param-name>
            <param-value>^(.+[.])(jsp|png|gif|jpg|js|css|jspx|jpeg|html|mp3|mp4|ico|zul|zhtml)$</param-value>
        </init-param>
    </filter>
    <filter-mapping>
        <filter-name>ShiroFilter</filter-name>
        <url-pattern>/*</url-pattern>
        <dispatcher>REQUEST</dispatcher>
        <dispatcher>FORWARD</dispatcher>
        <dispatcher>INCLUDE</dispatcher>
        <dispatcher>ERROR</dispatcher>
    </filter-mapping>

**Comment by cor3000** [comment]
Please configure SerializableUiFactory as in : https://www.zkoss.org/wiki/ZK_Developer's_Reference/Clustering/ZK_Configuration
