### ISSUE TITLE
Listbox#initRodSize generates too many NumberFormatExceptions

### ISSUE THREAD

**Issue by sirvaulterscoff** [zkoss/zk#831]
Our project heavily uses Listbox-es. While profiling application we noticed a lot of NumberFormatExceptions generated by zk. This lead us to Listbox#initRodSize and further to org.zkoss.zul.impl.Utils#getIntAttribute where both

`Object val = comp.getAttribute(name, recurse);`
and
`val = Library.getProperty(name);`

evaluates to null, allowing for further execution of Integer.parseInt on null value. Null-checking variable val after `val = Library.getProperty(name); `  seems like a good solution

**Comment by DevChu** [comment]
Hi, sirvaulterscoff. Could you provide a simple test case about this issue? That would be helpful. Thanks!

**Comment by scribetw** [comment]
Since the related PR was closed, close this issue.
